// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdSHeRFWCRKVZdIoTAxrpeZaJjNZq-8aM',
    appId: '1:555568965328:web:ab6757e5406a3af275a0d5',
    messagingSenderId: '555568965328',
    projectId: 'medi-locker-4bb57',
    authDomain: 'medi-locker-4bb57.firebaseapp.com',
    storageBucket: 'medi-locker-4bb57.firebasestorage.app',
    measurementId: 'G-R0L4FEX5MZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrAMC-iyaXevViGC7qXc9bSaa_g3aFOBA',
    appId: '1:555568965328:android:f82807c96c8482c175a0d5',
    messagingSenderId: '555568965328',
    projectId: 'medi-locker-4bb57',
    storageBucket: 'medi-locker-4bb57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJuKzY9JMlep0DDbSVUNoG8aAQxXwIXYw',
    appId: '1:555568965328:ios:66aaf63fdb517ca275a0d5',
    messagingSenderId: '555568965328',
    projectId: 'medi-locker-4bb57',
    storageBucket: 'medi-locker-4bb57.firebasestorage.app',
    iosBundleId: 'com.example.mediLocker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJuKzY9JMlep0DDbSVUNoG8aAQxXwIXYw',
    appId: '1:555568965328:ios:66aaf63fdb517ca275a0d5',
    messagingSenderId: '555568965328',
    projectId: 'medi-locker-4bb57',
    storageBucket: 'medi-locker-4bb57.firebasestorage.app',
    iosBundleId: 'com.example.mediLocker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdSHeRFWCRKVZdIoTAxrpeZaJjNZq-8aM',
    appId: '1:555568965328:web:803dba5636e205e075a0d5',
    messagingSenderId: '555568965328',
    projectId: 'medi-locker-4bb57',
    authDomain: 'medi-locker-4bb57.firebaseapp.com',
    storageBucket: 'medi-locker-4bb57.firebasestorage.app',
    measurementId: 'G-Q9GV73VJ2W',
  );
}
